[package]
name = "aaoca_compression_simulation"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1"
serde = { version = "1.0.219", features = ["derive"]}
image = "0.25.5"
rand = "0.9.1"
nalgebra = "*"
toml = "0.8.20"
rayon = "1.7.1"
crossbeam = "0.8.4"
anyhow = "1.0.97"
approx = "0.5"
serde_json = "1.0"