[general]
rest_input_path = "input/rest_csv_files"
stress_input_path = "input/stress_csv_files"
rest_output_path = "output/rest"
stress_output_path = "output/stress"
diastole_comparison_path = "output/diastole_comparison"
systole_comparison_path = "output/systole_comparison"
aligned_rest_path = "output/aligned_rest"
aligned_stress_path = "output/aligned_stress"

[processing]
run_process_case = false
run_phase_comparison = false
run_centerline_alignment = true

[settings]
